### ISSUE TITLE
 issue related to #9

### ISSUE THREAD

**Issue by Billy-80** [QuisApp/flutter_contacts#11]
Hi @joachimvalente ,this is a follow up on #9 the fix  works as expected yet I noticed another  issue only on Android. When using the same code of issue #9 to add an 'Address' (same code as issue #9 below)and the contact has an event item(birthday), the event item gets duplicated and de -duplicated with update() when adding and removing the address (dart removewhere to delete the address), same code has no issues on IOS.

fn1() async{

Contact testContact = await FlutterContacts.getContact('some ID');
Address testAddress = Address('test', customLabel: 'test' , label: AddressLabel.custom);
testContact.addresses.insert(0, testAddress);
await testContact.update();

}

**Comment by joachim-quis** [comment]
Hi @Billy-80

I looked into it a bit more. It has nothing to do with adding an address, or de-deduplicating properties. I could reproduce it on my device and on an emulator with this code (after commenting out the `deduplicateProperties()` function): https://gist.github.com/joachim-quis/dac953b3f45168484c5656de6e844e8e#file-main-dart-L84-L104

Steps:

* Create a contact
* Click the "Shopping" icon to add an event
* Click "Show" --> shows just one event
* Wait a bit (maybe 1-2 minutes)
* Click "Show" again -> shows two identical events

What I'm suspecting is happening is that Gmail synchronizes contacts behind the scenes, and for some reason duplicates that event. You can see that the default Android Contact app also seems to be de-duplicating events, since for that contact, even though there are two identical events, the app is only showing one:

![Screenshot_1618112178](https://user-images.githubusercontent.com/80799804/114291473-87ae6280-9a3c-11eb-9fa4-59d0171d877b.png)

This is the reason why I introduce `deduplicateProperties` in the first place, since that happened before for example with 3rd-party apps syncing in the background and duplicating phone numbers.

Feel free to re-open if there's anything else I can help with.

**Comment by Billy-80** [comment]
You're right, while testing with plane mode on to prevent sync I could not reproduce this anymore. It seems that the sync with google for events is quite problematic generally. Thank you.
